import { PERMISSIONS, ROLES } from "../constants/domain.js";

const MATRIX = {
  [ROLES.ADMIN]: new Set(Object.values(PERMISSIONS)),

  [ROLES.CLIENT]: new Set([
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.CRM_CREATE,
    PERMISSIONS.CRM_UPDATE,
    PERMISSIONS.CRM_ARCHIVE,
    PERMISSIONS.CRM_DELETE,
    PERMISSIONS.CRM_ASSIGN_OWNER,
    PERMISSIONS.CRM_MERGE,
    PERMISSIONS.CRM_SEND_EMAIL,
    PERMISSIONS.CRM_MANAGE_TASKS,
    PERMISSIONS.CRM_AUTO_ASSIGN,
    PERMISSIONS.TICKET_VIEW,
    PERMISSIONS.TICKET_UPDATE,
    PERMISSIONS.TICKET_ASSIGN,
    PERMISSIONS.CHAT_VIEW,
    PERMISSIONS.CHAT_TRANSFER,
    PERMISSIONS.CHAT_NOTE,
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.TEAM_VIEW
  ]),

  // Manager: full CRM control + monitoring + delete
  [ROLES.MANAGER]: new Set([
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.CRM_CREATE,
    PERMISSIONS.CRM_UPDATE,
    PERMISSIONS.CRM_ARCHIVE,
    PERMISSIONS.CRM_DELETE,
    PERMISSIONS.CRM_ASSIGN_OWNER,
    PERMISSIONS.CRM_MERGE,
    PERMISSIONS.CRM_SEND_EMAIL,
    PERMISSIONS.CRM_MANAGE_TASKS,
    PERMISSIONS.CRM_AUTO_ASSIGN,
    PERMISSIONS.TICKET_VIEW,
    PERMISSIONS.TICKET_UPDATE,
    PERMISSIONS.TICKET_ASSIGN,
    PERMISSIONS.CHAT_VIEW,
    PERMISSIONS.CHAT_NOTE,
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.TEAM_VIEW
  ]),

  // Sales: own assigned leads only, no delete/assign/archive
  [ROLES.SALES]: new Set([
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.CRM_CREATE,
    PERMISSIONS.CRM_UPDATE,
    PERMISSIONS.CRM_SEND_EMAIL,
    PERMISSIONS.CRM_MANAGE_TASKS,
    PERMISSIONS.TICKET_VIEW,
    PERMISSIONS.TICKET_UPDATE,
    PERMISSIONS.CHAT_VIEW,
    PERMISSIONS.CHAT_NOTE,
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.REPORTS_VIEW
  ]),

  [ROLES.AGENT]: new Set([
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.TICKET_VIEW,
    PERMISSIONS.TICKET_UPDATE,
    PERMISSIONS.CHAT_VIEW,
    PERMISSIONS.CHAT_TRANSFER,
    PERMISSIONS.CHAT_NOTE,
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.NOTIFICATION_VIEW
  ]),

  [ROLES.USER]: new Set([
    PERMISSIONS.TICKET_VIEW,
    PERMISSIONS.CHAT_VIEW,
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.NOTIFICATION_VIEW
  ])
};

export function hasPermission(user, permission) {
  if (!user?.role) return false;
  return MATRIX[user.role]?.has(permission) || false;
}
